import Head from 'next/head'
import Company from '../components/company-progress'
import CreateCompany from '../components/create-company/create-company'
import { Button, Container } from '../components/shared.styles'
import { useGeneralContext } from '../providers/general'

export default function Home({ clearCache }) {
  const { values: { companyId } } = useGeneralContext()
  return (
    <>
      <Head>
        <title>Company progress tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {!companyId && <CreateCompany />}
        {!!companyId && <Company id={companyId} />}
      </Container>
    </>
  )
}
