import Head from 'next/head'
import Company from '../components/company'
import { Button } from '../components/company/company.styles'

export default function Home({clearCache}) {
  return (
    <>
      <Head>
        <title>Company progress tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Company id={"company_1"} />
      <Button onClick={()=>clearCache()}>{`See what's next :)`}</Button>
    </>
  )
}
